// 테이블명 상수 — v2_ 접두사 관리
// 전환 완료 후: PREFIX를 "" 로 변경하면 끝
const PREFIX = "v2_";

export const T = {
  profiles: `${PREFIX}profiles`,
  user_credits: `${PREFIX}user_credits`,
  polar_balances: `${PREFIX}polar_balances`,
  polar_orders: `${PREFIX}polar_orders`,
  polar_transactions: `${PREFIX}polar_transactions`,
  questions: `${PREFIX}questions`,
  master_questions: `${PREFIX}master_questions`,
  submissions: `${PREFIX}submissions`,
  submission_questions: `${PREFIX}submission_questions`,
  submission_combos: `${PREFIX}submission_combos`,
  scripts: `${PREFIX}scripts`,
  script_packages: `${PREFIX}script_packages`,
  script_specs: `${PREFIX}script_specs`,
  ai_prompt_templates: `${PREFIX}ai_prompt_templates`,
  mock_test_sessions: `${PREFIX}mock_test_sessions`,
  mock_test_answers: `${PREFIX}mock_test_answers`,
  mock_test_evaluations: `${PREFIX}mock_test_evaluations`,
  mock_test_consults: `${PREFIX}mock_test_consults`,
  mock_test_reports: `${PREFIX}mock_test_reports`,
  mock_test_eval_settings: `${PREFIX}mock_test_eval_settings`,
  evaluation_prompts: `${PREFIX}evaluation_prompts`,
  evaluation_criteria: `${PREFIX}evaluation_criteria`,
  task_fulfillment_checklists: `${PREFIX}task_fulfillment_checklists`,
  tutoring_sessions: `${PREFIX}tutoring_sessions`,
  tutoring_focuses: `${PREFIX}tutoring_focuses`,
  tutoring_drills: `${PREFIX}tutoring_drills`,
  tutoring_attempts: `${PREFIX}tutoring_attempts`,
  tutoring_retests: `${PREFIX}tutoring_retests`,
  type_templates: `${PREFIX}type_templates`,
  level_modifiers: `${PREFIX}level_modifiers`,
  shadowing_sessions: `${PREFIX}shadowing_sessions`,
  shadowing_evaluations: `${PREFIX}shadowing_evaluations`,
  opic_tips: `${PREFIX}opic_tips`,
  orders: `${PREFIX}orders`,
  beta_applications: `${PREFIX}beta_applications`,
  announcements: `${PREFIX}announcements`,
  admin_audit_log: `${PREFIX}admin_audit_log`,
  user_activity_log: `${PREFIX}user_activity_log`,
  api_usage_logs: `${PREFIX}api_usage_logs`,
} as const;
