// 테이블명 상수
export const T = {
  profiles: "profiles",
  user_credits: "user_credits",
  polar_balances: "polar_balances",
  polar_orders: "polar_orders",
  polar_transactions: "polar_transactions",
  questions: "questions",
  master_questions: "master_questions",
  submissions: "submissions",
  submission_questions: "submission_questions",
  submission_combos: "submission_combos",
  scripts: "scripts",
  script_packages: "script_packages",
  script_specs: "script_specs",
  ai_prompt_templates: "ai_prompt_templates",
  mock_test_sessions: "mock_test_sessions",
  mock_test_answers: "mock_test_answers",
  mock_test_evaluations: "mock_test_evaluations",
  mock_test_consults: "mock_test_consults",
  mock_test_reports: "mock_test_reports",
  mock_test_eval_settings: "mock_test_eval_settings",
  evaluation_prompts: "evaluation_prompts",
  evaluation_criteria: "evaluation_criteria",
  task_fulfillment_checklists: "task_fulfillment_checklists",
  tutoring_sessions: "tutoring_sessions",
  tutoring_focuses: "tutoring_focuses",
  tutoring_drills: "tutoring_drills",
  tutoring_attempts: "tutoring_attempts",
  tutoring_retests: "tutoring_retests",
  type_templates: "type_templates",
  level_modifiers: "level_modifiers",
  shadowing_sessions: "shadowing_sessions",
  shadowing_evaluations: "shadowing_evaluations",
  opic_tips: "opic_tips",
  orders: "orders",
  beta_applications: "beta_applications",
  announcements: "announcements",
  system_settings: "system_settings",
  sponsorships: "sponsorships",
  admin_audit_log: "admin_audit_log",
  user_activity_log: "user_activity_log",
  api_usage_logs: "api_usage_logs",
} as const;

// RPC 함수명 상수
export const RPC = {
  polar_get_balance: "polar_get_balance",
  polar_deduct_balance: "polar_deduct_balance",
  polar_charge_balance: "polar_charge_balance",
  polar_refund_balance: "polar_refund_balance",
  polar_admin_adjust_balance: "polar_admin_adjust_balance",
  process_polar_payment: "process_polar_payment",
  get_beta_stats: "get_beta_stats",
  get_dau_count: "get_dau_count",
  refund_script_credit: "refund_script_credit", // no-op — scripts EF 호환용
  polar_reverse_charge: "polar_reverse_charge",
  check_balance: "check_balance",
  handle_new_user: "handle_new_user",
  handle_new_user_credits: "handle_new_user_credits",
  handle_new_user_polar_balance: "handle_new_user_polar_balance",
  update_updated_at: "update_updated_at",
  expire_beta_plans: "expire_beta_plans",
  grant_beta_access: "grant_beta_access",
  revoke_beta_access: "revoke_beta_access",
  get_beta_users: "get_beta_users",
  find_user_by_email: "find_user_by_email",
  process_payment: "process_payment",
  get_user_cost_summary: "get_user_cost_summary",
  get_user_usage_summary: "get_user_usage_summary",
  increment_completed_prescriptions: "increment_completed_prescriptions",
  increment_training_count: "increment_training_count",
} as const;
