-- =============================================================================
-- 034_v2_tables.sql
-- v2_ 접두사를 붙인 하루오픽 전체 테이블 복제
-- system_settings 제외 (v1과 공유)
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. 독립 테이블 (FK 없거나 auth.users만 참조)
-- ─────────────────────────────────────────────────────────────────────────────

-- profiles
CREATE TABLE v2_profiles (
  id uuid NOT NULL REFERENCES auth.users(id),
  email text NOT NULL,
  display_name text,
  target_grade text,
  avatar_url text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT v2_profiles_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_profiles_insert ON v2_profiles FOR INSERT TO public WITH CHECK (true);
CREATE POLICY v2_profiles_select_own ON v2_profiles FOR SELECT TO public USING (auth.uid() = id);
CREATE POLICY v2_profiles_update_own ON v2_profiles FOR UPDATE TO public USING (auth.uid() = id);

-- user_credits
CREATE TABLE v2_user_credits (
  user_id uuid NOT NULL REFERENCES auth.users(id),
  current_plan text NOT NULL DEFAULT 'free',
  mock_exam_credits integer NOT NULL DEFAULT 0,
  script_credits integer NOT NULL DEFAULT 0,
  plan_expires_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  plan_mock_exam_credits integer NOT NULL DEFAULT 0,
  plan_script_credits integer NOT NULL DEFAULT 0,
  plan_tutoring_credits integer NOT NULL DEFAULT 0,
  tutoring_credits integer NOT NULL DEFAULT 0,
  balance_krw integer NOT NULL DEFAULT 0,
  CONSTRAINT v2_user_credits_pkey PRIMARY KEY (user_id)
);
ALTER TABLE v2_user_credits ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_user_credits_select_own ON v2_user_credits FOR SELECT TO public
  USING (auth.uid() = user_id OR ((auth.jwt() -> 'app_metadata') ->> 'role') = 'admin');

-- questions
CREATE TABLE v2_questions (
  id text NOT NULL,
  category text NOT NULL,
  sub_category text NOT NULL DEFAULT '-',
  topic text NOT NULL,
  survey_type text NOT NULL,
  question_english text NOT NULL DEFAULT '',
  question_korean text NOT NULL DEFAULT '',
  question_short text NOT NULL DEFAULT '',
  question_type_kor text NOT NULL DEFAULT '',
  question_type_eng text NOT NULL DEFAULT '',
  tag text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  audio_url text DEFAULT '',
  CONSTRAINT v2_questions_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_questions_select_all ON v2_questions FOR SELECT TO public USING (true);
CREATE INDEX v2_idx_questions_category ON v2_questions USING btree (category);
CREATE INDEX v2_idx_questions_category_topic ON v2_questions USING btree (category, topic);
CREATE INDEX v2_idx_questions_question_type_eng ON v2_questions USING btree (question_type_eng);
CREATE INDEX v2_idx_questions_survey_type ON v2_questions USING btree (survey_type);
CREATE INDEX v2_idx_questions_tag ON v2_questions USING btree (tag);
CREATE INDEX v2_idx_questions_topic ON v2_questions USING btree (topic);

-- master_questions
CREATE TABLE v2_master_questions (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  question_id text NOT NULL,
  survey_type text NOT NULL,
  topic_category text NOT NULL,
  topic text NOT NULL,
  question_title text,
  question_english text NOT NULL,
  question_korean text NOT NULL,
  question_type text,
  audio_url text,
  audio_generated_at timestamptz,
  audio_voice text DEFAULT 'Aoede',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT v2_master_questions_pkey PRIMARY KEY (id),
  CONSTRAINT v2_master_questions_question_id_key UNIQUE (question_id)
);
ALTER TABLE v2_master_questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_master_questions_select ON v2_master_questions FOR SELECT TO authenticated USING (true);
CREATE INDEX v2_idx_master_questions_answer_type ON v2_master_questions USING btree (question_type);
CREATE INDEX v2_idx_master_questions_survey_type ON v2_master_questions USING btree (survey_type);
CREATE INDEX v2_idx_master_questions_topic ON v2_master_questions USING btree (topic);
CREATE INDEX v2_idx_master_questions_topic_category ON v2_master_questions USING btree (topic_category);

-- ai_prompt_templates
CREATE TABLE v2_ai_prompt_templates (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  template_id text NOT NULL,
  prompt_name text,
  system_prompt text NOT NULL,
  user_template text,
  model text DEFAULT 'gpt-4.1',
  temperature numeric(2,1) DEFAULT 0.8,
  max_tokens integer DEFAULT 4000,
  response_format text DEFAULT 'json_schema',
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT v2_ai_prompt_templates_pkey PRIMARY KEY (id),
  CONSTRAINT v2_ai_prompt_templates_template_id_key UNIQUE (template_id)
);
ALTER TABLE v2_ai_prompt_templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_ai_prompt_templates_read ON v2_ai_prompt_templates FOR SELECT TO public USING (true);

-- announcements
CREATE TABLE v2_announcements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  type text NOT NULL DEFAULT 'notice',
  target_audience text DEFAULT 'all',
  is_active boolean DEFAULT true,
  start_at timestamptz DEFAULT now(),
  end_at timestamptz,
  created_by uuid,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT v2_announcements_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_announcements ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_announcements_admin_all ON v2_announcements FOR ALL TO public
  USING (EXISTS (SELECT 1 FROM auth.users WHERE users.id = auth.uid() AND (users.raw_app_meta_data ->> 'role') = 'admin'));
CREATE POLICY v2_announcements_anon_read_active ON v2_announcements FOR SELECT TO public
  USING (is_active = true AND (end_at IS NULL OR end_at > now()));

-- evaluation_criteria
CREATE TABLE v2_evaluation_criteria (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  target_grade text NOT NULL,
  question_type text NOT NULL,
  criteria_text text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT v2_evaluation_criteria_pkey PRIMARY KEY (id),
  CONSTRAINT v2_evaluation_criteria_target_grade_question_type_key UNIQUE (target_grade, question_type)
);
ALTER TABLE v2_evaluation_criteria ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_evaluation_criteria_select ON v2_evaluation_criteria FOR SELECT TO authenticated USING (true);
CREATE POLICY v2_evaluation_criteria_service ON v2_evaluation_criteria FOR ALL TO service_role USING (true) WITH CHECK (true);

-- evaluation_prompts
CREATE TABLE v2_evaluation_prompts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL,
  prompt_text text NOT NULL,
  description text,
  model text DEFAULT 'gpt-4.1',
  prompt_version text DEFAULT 'v1',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT v2_evaluation_prompts_pkey PRIMARY KEY (id),
  CONSTRAINT v2_evaluation_prompts_key_key UNIQUE (key)
);
ALTER TABLE v2_evaluation_prompts ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_evaluation_prompts_select ON v2_evaluation_prompts FOR SELECT TO authenticated USING (true);
CREATE POLICY v2_evaluation_prompts_service ON v2_evaluation_prompts FOR ALL TO service_role USING (true) WITH CHECK (true);

-- level_modifiers
CREATE TABLE v2_level_modifiers (
  level_code text NOT NULL,
  level_label text NOT NULL,
  target_text_type text,
  sentence_target jsonb,
  word_count_target jsonb,
  duration_target_sec jsonb,
  required_discourse_features text[],
  feedback_policy jsonb,
  pass_adjustments jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT v2_level_modifiers_pkey PRIMARY KEY (level_code)
);
ALTER TABLE v2_level_modifiers ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_level_modifiers_read_all ON v2_level_modifiers FOR SELECT TO public USING (true);

-- type_templates
CREATE TABLE v2_type_templates (
  type_code text NOT NULL,
  type_label_ko text NOT NULL,
  db_question_types text[] NOT NULL,
  purpose text,
  core_skill_targets text[],
  default_slot_order text[],
  slot_definitions jsonb,
  default_pass_criteria text[],
  default_retest_criteria text[],
  layer1_markers jsonb,
  graduation_relevance text DEFAULT 'medium',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT v2_type_templates_pkey PRIMARY KEY (type_code)
);
ALTER TABLE v2_type_templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_type_templates_read_all ON v2_type_templates FOR SELECT TO public USING (true);

-- task_fulfillment_checklists
CREATE TABLE v2_task_fulfillment_checklists (
  question_type text NOT NULL,
  label text NOT NULL,
  required jsonb NOT NULL DEFAULT '[]',
  advanced jsonb NOT NULL DEFAULT '[]',
  ideal_flow text NOT NULL DEFAULT '',
  common_mistakes jsonb NOT NULL DEFAULT '[]',
  core_prescription text NOT NULL DEFAULT '',
  feedback_tone text NOT NULL DEFAULT '',
  start_template text NOT NULL DEFAULT '',
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT v2_task_fulfillment_checklists_pkey PRIMARY KEY (question_type)
);
ALTER TABLE v2_task_fulfillment_checklists ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_task_fulfillment_checklists_read ON v2_task_fulfillment_checklists FOR SELECT TO public USING (true);

-- opic_tips
CREATE TABLE v2_opic_tips (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  category text NOT NULL,
  question_type text,
  applicable_levels text[] NOT NULL DEFAULT '{IL,IM1,IM2,IM3,IH,AL}',
  title text NOT NULL,
  expression text NOT NULL,
  description text,
  display_order smallint DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT v2_opic_tips_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_opic_tips ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_opic_tips_public_read ON v2_opic_tips FOR SELECT TO public USING (true);
CREATE INDEX v2_idx_opic_tips_answer_type ON v2_opic_tips USING btree (question_type);
CREATE INDEX v2_idx_opic_tips_category ON v2_opic_tips USING btree (category);

-- script_specs
CREATE TABLE v2_script_specs (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  guide_id text NOT NULL,
  question_type text NOT NULL,
  target_grade text NOT NULL,
  total_slots smallint NOT NULL,
  level_constraints text NOT NULL,
  slot_structure text NOT NULL,
  example_output jsonb NOT NULL,
  eval_criteria text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT v2_script_specs_pkey PRIMARY KEY (id),
  CONSTRAINT v2_script_specs_guide_id_key UNIQUE (guide_id)
);
ALTER TABLE v2_script_specs ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_script_specs_read ON v2_script_specs FOR SELECT TO public USING (true);
CREATE INDEX v2_idx_script_specs_answer_type ON v2_script_specs USING btree (question_type);
CREATE INDEX v2_idx_script_specs_target_level ON v2_script_specs USING btree (target_grade);

-- mock_test_eval_settings
CREATE TABLE v2_mock_test_eval_settings (
  id integer NOT NULL DEFAULT 1,
  re_checkbox_pass_threshold numeric NOT NULL DEFAULT 0.80,
  re_floor_nh numeric NOT NULL DEFAULT 0.45,
  re_floor_il numeric NOT NULL DEFAULT 0.65,
  re_floor_im1 numeric NOT NULL DEFAULT 0.75,
  re_floor_im2 numeric NOT NULL DEFAULT 0.95,
  re_ceiling_broke_down numeric NOT NULL DEFAULT 0.70,
  re_ceiling_respond numeric NOT NULL DEFAULT 0.90,
  re_sympathetic_low numeric NOT NULL DEFAULT 50,
  re_sympathetic_mid numeric NOT NULL DEFAULT 70,
  re_sympathetic_at_times numeric NOT NULL DEFAULT 85,
  re_sympathetic_pron_weight numeric NOT NULL DEFAULT 0.60,
  re_al_pass_threshold numeric NOT NULL DEFAULT 0.70,
  re_q12_gatekeeper_threshold numeric NOT NULL DEFAULT 0.50,
  judge_model text NOT NULL DEFAULT 'gpt-4.1-mini',
  judge_temperature numeric NOT NULL DEFAULT 0.20,
  judge_max_tokens integer NOT NULL DEFAULT 6000,
  coach_model text NOT NULL DEFAULT 'gpt-4.1',
  coach_temperature numeric NOT NULL DEFAULT 0.40,
  coach_max_tokens integer NOT NULL DEFAULT 8000,
  report_model text NOT NULL DEFAULT 'gpt-4.1',
  report_temperature numeric NOT NULL DEFAULT 0.40,
  report_max_tokens integer NOT NULL DEFAULT 12000,
  growth_model text NOT NULL DEFAULT 'gpt-4.1-mini',
  growth_temperature numeric NOT NULL DEFAULT 0.50,
  growth_max_tokens integer NOT NULL DEFAULT 3000,
  enabled_description boolean NOT NULL DEFAULT true,
  enabled_routine boolean NOT NULL DEFAULT true,
  enabled_asking_questions boolean NOT NULL DEFAULT true,
  enabled_comparison boolean NOT NULL DEFAULT true,
  enabled_past_experience boolean NOT NULL DEFAULT true,
  enabled_suggest_alternatives boolean NOT NULL DEFAULT true,
  enabled_comparison_change boolean NOT NULL DEFAULT true,
  enabled_social_issue boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT v2_mock_test_eval_settings_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_mock_test_eval_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_admin_select_eval_settings ON v2_mock_test_eval_settings FOR SELECT TO public
  USING (((auth.jwt() -> 'app_metadata') ->> 'role') = 'admin');
CREATE POLICY v2_admin_update_eval_settings ON v2_mock_test_eval_settings FOR UPDATE TO public
  USING (((auth.jwt() -> 'app_metadata') ->> 'role') = 'admin');

-- orders
CREATE TABLE v2_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id),
  product_id text NOT NULL,
  order_name text NOT NULL,
  amount integer NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  payment_id text,
  pg_provider text,
  pg_tx_id text,
  pay_method text,
  paid_at timestamptz,
  receipt_url text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT v2_orders_pkey PRIMARY KEY (id),
  CONSTRAINT v2_orders_payment_id_unique UNIQUE (payment_id)
);
ALTER TABLE v2_orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_orders_select_own ON v2_orders FOR SELECT TO public
  USING (auth.uid() = user_id OR ((auth.jwt() -> 'app_metadata') ->> 'role') = 'admin');
CREATE INDEX v2_idx_orders_payment_id ON v2_orders USING btree (payment_id);
CREATE INDEX v2_idx_orders_status ON v2_orders USING btree (status);
CREATE INDEX v2_idx_orders_user_id ON v2_orders USING btree (user_id);

-- polar_balances
CREATE TABLE v2_polar_balances (
  user_id uuid NOT NULL REFERENCES auth.users(id),
  balance_krw integer NOT NULL DEFAULT 0,
  total_charged integer NOT NULL DEFAULT 0,
  total_used integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT v2_polar_balances_pkey PRIMARY KEY (user_id)
);
ALTER TABLE v2_polar_balances ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_polar_balances_select_own ON v2_polar_balances FOR SELECT TO public
  USING (auth.uid() = user_id);

-- polar_orders
CREATE TABLE v2_polar_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id),
  polar_checkout_id text NOT NULL,
  polar_product_id text,
  product_type text NOT NULL,
  amount integer NOT NULL,
  credit_amount integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'paid',
  paid_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT v2_polar_orders_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_polar_orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_polar_orders_select_own ON v2_polar_orders FOR SELECT TO public
  USING (auth.uid() = user_id);
CREATE UNIQUE INDEX v2_idx_polar_orders_checkout_id ON v2_polar_orders USING btree (polar_checkout_id);
CREATE INDEX v2_idx_polar_orders_user_id ON v2_polar_orders USING btree (user_id);

-- polar_transactions
CREATE TABLE v2_polar_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id),
  type text NOT NULL,
  amount integer NOT NULL,
  balance_after integer NOT NULL,
  description text NOT NULL,
  ref_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT v2_polar_transactions_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_polar_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_polar_transactions_select_own ON v2_polar_transactions FOR SELECT TO public
  USING (auth.uid() = user_id);
CREATE INDEX v2_idx_polar_transactions_created_at ON v2_polar_transactions USING btree (created_at DESC);
CREATE INDEX v2_idx_polar_transactions_user_id ON v2_polar_transactions USING btree (user_id);

-- admin_audit_log
CREATE TABLE v2_admin_audit_log (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  admin_id uuid NOT NULL,
  action text NOT NULL,
  target_type text,
  target_id text,
  details jsonb DEFAULT '{}',
  ip_address text,
  created_at timestamptz DEFAULT now(),
  admin_email text,
  CONSTRAINT v2_admin_audit_log_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_admin_audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_admin_audit_log_select ON v2_admin_audit_log FOR SELECT TO public
  USING (((auth.jwt() -> 'app_metadata') ->> 'role') = 'admin');
CREATE INDEX v2_idx_audit_log_action ON v2_admin_audit_log USING btree (action);
CREATE INDEX v2_idx_audit_log_admin_id ON v2_admin_audit_log USING btree (admin_id);
CREATE INDEX v2_idx_audit_log_created_at ON v2_admin_audit_log USING btree (created_at DESC);

-- api_usage_logs
CREATE TABLE v2_api_usage_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id),
  session_type text NOT NULL,
  session_id text,
  feature text NOT NULL,
  service text NOT NULL,
  model text NOT NULL,
  ef_name text NOT NULL,
  tokens_in integer,
  tokens_out integer,
  audio_duration_sec numeric(10,2),
  text_length integer,
  cost_usd numeric(10,6) NOT NULL DEFAULT 0,
  processing_time_ms integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT v2_api_usage_logs_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_api_usage_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_admin_view_usage_logs ON v2_api_usage_logs FOR SELECT TO public
  USING (((auth.jwt() -> 'app_metadata') ->> 'role') = 'admin');
CREATE POLICY v2_users_view_own_usage_logs ON v2_api_usage_logs FOR SELECT TO public
  USING (auth.uid() = user_id);
CREATE INDEX v2_idx_api_usage_created_at ON v2_api_usage_logs USING btree (created_at DESC);
CREATE INDEX v2_idx_api_usage_session ON v2_api_usage_logs USING btree (session_type, session_id) WHERE session_id IS NOT NULL;
CREATE INDEX v2_idx_api_usage_user_id ON v2_api_usage_logs USING btree (user_id);
CREATE INDEX v2_idx_api_usage_user_period ON v2_api_usage_logs USING btree (user_id, created_at DESC);

-- beta_applications
CREATE TABLE v2_beta_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id),
  kakao_nickname text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  rejected_reason text,
  reviewed_by uuid REFERENCES auth.users(id),
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT v2_beta_applications_pkey PRIMARY KEY (id),
  CONSTRAINT v2_beta_one_per_user UNIQUE (user_id)
);
ALTER TABLE v2_beta_applications ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_beta_insert_own ON v2_beta_applications FOR INSERT TO public WITH CHECK (auth.uid() = user_id);
CREATE POLICY v2_beta_select_own ON v2_beta_applications FOR SELECT TO public USING (auth.uid() = user_id);
CREATE INDEX v2_idx_beta_applications_status ON v2_beta_applications USING btree (status);

-- user_activity_log
CREATE TABLE v2_user_activity_log (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL,
  action text NOT NULL,
  metadata jsonb DEFAULT '{}',
  created_at timestamptz DEFAULT now(),
  CONSTRAINT v2_user_activity_log_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_user_activity_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_admin_read_activity ON v2_user_activity_log FOR SELECT TO public
  USING ((EXISTS (SELECT 1 FROM auth.users WHERE users.id = auth.uid() AND (users.raw_app_meta_data ->> 'role') = 'admin')) OR auth.uid() = user_id);
CREATE POLICY v2_insert_own_activity ON v2_user_activity_log FOR INSERT TO public WITH CHECK (auth.uid() = user_id);
CREATE INDEX v2_idx_activity_log_action ON v2_user_activity_log USING btree (action, created_at DESC);
CREATE INDEX v2_idx_activity_log_user ON v2_user_activity_log USING btree (user_id, created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. submissions (FK: auth.users)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE v2_submissions (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL REFERENCES auth.users(id),
  exam_date date NOT NULL,
  achieved_level text,
  exam_purpose text NOT NULL,
  study_methods text[] NOT NULL,
  prep_duration text NOT NULL,
  attempt_count text NOT NULL,
  perceived_difficulty text NOT NULL,
  actual_duration text NOT NULL,
  one_line_review varchar(100),
  tips varchar(300),
  status text NOT NULL DEFAULT 'draft',
  step_completed smallint NOT NULL DEFAULT 1,
  submitted_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  pre_exam_level text NOT NULL,
  used_recommended_survey boolean NOT NULL DEFAULT true,
  survey_occupation text,
  survey_student text,
  survey_course text,
  survey_housing text,
  survey_leisure text,
  survey_hobbies text,
  survey_sports text,
  survey_travel text,
  exam_difficulty text,
  credit_granted boolean NOT NULL DEFAULT false,
  source text NOT NULL DEFAULT 'user',
  exam_approved text DEFAULT 'pending',
  exam_approved_at timestamptz,
  CONSTRAINT v2_submissions_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_submissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_submissions_delete_own ON v2_submissions FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY v2_submissions_insert_own ON v2_submissions FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY v2_submissions_select ON v2_submissions FOR SELECT TO public
  USING (auth.uid() = user_id OR status = 'complete' OR ((auth.jwt() -> 'app_metadata') ->> 'role') = 'admin');
CREATE POLICY v2_submissions_update_own ON v2_submissions FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE INDEX v2_idx_submissions_exam_approved ON v2_submissions USING btree (exam_approved) WHERE status = 'complete';
CREATE INDEX v2_idx_submissions_exam_date ON v2_submissions USING btree (exam_date);
CREATE INDEX v2_idx_submissions_source ON v2_submissions USING btree (source);
CREATE INDEX v2_idx_submissions_status ON v2_submissions USING btree (status);
CREATE INDEX v2_idx_submissions_user_id ON v2_submissions USING btree (user_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. 자식 테이블 (FK → submissions, questions)
-- ─────────────────────────────────────────────────────────────────────────────

-- submission_questions
CREATE TABLE v2_submission_questions (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  submission_id integer NOT NULL REFERENCES v2_submissions(id),
  question_number smallint NOT NULL,
  combo_type text NOT NULL,
  topic text NOT NULL,
  question_id text REFERENCES v2_questions(id),
  custom_question_text text,
  is_not_remembered boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT v2_submission_questions_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_submission_questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_sq_delete_own ON v2_submission_questions FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM v2_submissions s WHERE s.id = v2_submission_questions.submission_id AND s.user_id = auth.uid()));
CREATE POLICY v2_sq_insert_own ON v2_submission_questions FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM v2_submissions s WHERE s.id = v2_submission_questions.submission_id AND s.user_id = auth.uid()));
CREATE POLICY v2_sq_select ON v2_submission_questions FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM v2_submissions s WHERE s.id = v2_submission_questions.submission_id AND (s.user_id = auth.uid() OR s.status = 'complete')));
CREATE INDEX v2_idx_sq_question_id ON v2_submission_questions USING btree (question_id);
CREATE INDEX v2_idx_sq_submission_id ON v2_submission_questions USING btree (submission_id);
CREATE INDEX v2_idx_submission_questions_topic ON v2_submission_questions USING btree (topic);

-- submission_combos
CREATE TABLE v2_submission_combos (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  submission_id integer NOT NULL REFERENCES v2_submissions(id),
  combo_type text NOT NULL,
  topic text NOT NULL,
  question_ids text[] NOT NULL,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT v2_submission_combos_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_submission_combos ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_sc_delete_own ON v2_submission_combos FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM v2_submissions s WHERE s.id = v2_submission_combos.submission_id AND s.user_id = auth.uid()));
CREATE POLICY v2_sc_insert_own ON v2_submission_combos FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM v2_submissions s WHERE s.id = v2_submission_combos.submission_id AND s.user_id = auth.uid()));
CREATE POLICY v2_sc_select_anon ON v2_submission_combos FOR SELECT TO anon USING (combo_type = 'advance');
CREATE POLICY v2_sc_select_authenticated ON v2_submission_combos FOR SELECT TO authenticated USING (true);
CREATE INDEX v2_idx_sc_submission_id ON v2_submission_combos USING btree (submission_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. scripts (FK → questions, auth.users)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE v2_scripts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id),
  question_id text NOT NULL REFERENCES v2_questions(id),
  source text NOT NULL DEFAULT 'generate',
  title text,
  english_text text NOT NULL,
  korean_translation text,
  paragraphs jsonb,
  total_slots smallint,
  category text,
  topic text,
  question_korean text,
  question_english text,
  user_story text,
  user_original_answer text,
  target_grade text,
  question_type text,
  ai_model text DEFAULT 'gpt-4.1',
  word_count integer,
  generation_time integer,
  key_expressions jsonb DEFAULT '[]',
  highlighted_script text,
  status text NOT NULL DEFAULT 'draft',
  refine_count smallint NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT v2_scripts_pkey PRIMARY KEY (id),
  CONSTRAINT v2_scripts_user_id_question_id_key UNIQUE (user_id, question_id)
);
ALTER TABLE v2_scripts ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_scripts_delete_own ON v2_scripts FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY v2_scripts_insert_own ON v2_scripts FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY v2_scripts_select_own ON v2_scripts FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY v2_scripts_update_own ON v2_scripts FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE INDEX v2_idx_scripts_category ON v2_scripts USING btree (category);
CREATE INDEX v2_idx_scripts_question_id ON v2_scripts USING btree (question_id);
CREATE INDEX v2_idx_scripts_source ON v2_scripts USING btree (source);
CREATE INDEX v2_idx_scripts_status ON v2_scripts USING btree (status);
CREATE INDEX v2_idx_scripts_user_id ON v2_scripts USING btree (user_id);

-- script_packages (FK → scripts)
CREATE TABLE v2_script_packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id),
  script_id uuid NOT NULL REFERENCES v2_scripts(id),
  status text DEFAULT 'processing',
  progress smallint DEFAULT 0,
  wav_file_path text,
  json_file_path text,
  timestamp_data jsonb,
  wav_file_size integer,
  tts_voice text DEFAULT 'Mark',
  error_message text,
  created_at timestamptz DEFAULT now(),
  completed_at timestamptz,
  CONSTRAINT v2_script_packages_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_script_packages ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_script_packages_delete_own ON v2_script_packages FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY v2_script_packages_insert_own ON v2_script_packages FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY v2_script_packages_select_own ON v2_script_packages FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY v2_script_packages_update_own ON v2_script_packages FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE INDEX v2_idx_script_packages_script_id ON v2_script_packages USING btree (script_id);
CREATE INDEX v2_idx_script_packages_status ON v2_script_packages USING btree (status);
CREATE INDEX v2_idx_script_packages_user_id ON v2_script_packages USING btree (user_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. shadowing (FK → scripts, script_packages)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE v2_shadowing_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id),
  package_id uuid NOT NULL REFERENCES v2_script_packages(id),
  script_id uuid NOT NULL REFERENCES v2_scripts(id),
  question_text text,
  question_korean text,
  topic text,
  status text DEFAULT 'active',
  audio_duration numeric(8,2),
  started_at timestamptz DEFAULT now(),
  completed_at timestamptz,
  CONSTRAINT v2_shadowing_sessions_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_shadowing_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_shadowing_sessions_all_own ON v2_shadowing_sessions FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE INDEX v2_idx_shadowing_sessions_script ON v2_shadowing_sessions USING btree (script_id);
CREATE INDEX v2_idx_shadowing_sessions_user ON v2_shadowing_sessions USING btree (user_id);

CREATE TABLE v2_shadowing_evaluations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES v2_shadowing_sessions(id),
  user_id uuid NOT NULL REFERENCES auth.users(id),
  transcript text NOT NULL,
  word_count integer,
  pronunciation numeric(3,1),
  fluency numeric(3,1),
  grammar numeric(3,1),
  vocabulary numeric(3,1),
  content_score numeric(3,1),
  overall_score numeric(5,1),
  estimated_level text,
  script_utilization numeric(5,1),
  strengths text[],
  weaknesses text[],
  suggestions text[],
  script_analysis jsonb,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT v2_shadowing_evaluations_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_shadowing_evaluations ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_shadowing_evaluations_insert_own ON v2_shadowing_evaluations FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY v2_shadowing_evaluations_select_own ON v2_shadowing_evaluations FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE INDEX v2_idx_shadowing_evaluations_session ON v2_shadowing_evaluations USING btree (session_id);
CREATE INDEX v2_idx_shadowing_evaluations_user ON v2_shadowing_evaluations USING btree (user_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. mock_test (FK → submissions, auth.users)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE v2_mock_test_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id),
  submission_id integer NOT NULL REFERENCES v2_submissions(id),
  mode text NOT NULL,
  status text NOT NULL DEFAULT 'active',
  question_ids text[] NOT NULL,
  current_question smallint DEFAULT 1,
  total_questions smallint DEFAULT 15,
  holistic_status text DEFAULT 'pending',
  report_retry_count smallint DEFAULT 0,
  report_error text,
  started_at timestamptz DEFAULT now(),
  completed_at timestamptz,
  expires_at timestamptz NOT NULL,
  CONSTRAINT v2_mock_test_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT v2_mock_test_sessions_session_id_key UNIQUE (session_id)
);
ALTER TABLE v2_mock_test_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_mock_sessions_insert_own ON v2_mock_test_sessions FOR INSERT TO public WITH CHECK (auth.uid() = user_id);
CREATE POLICY v2_mock_sessions_select_own ON v2_mock_test_sessions FOR SELECT TO public
  USING (auth.uid() = user_id OR ((auth.jwt() -> 'app_metadata') ->> 'role') = 'admin');
CREATE POLICY v2_mock_sessions_update_own ON v2_mock_test_sessions FOR UPDATE TO public USING (auth.uid() = user_id);
CREATE INDEX v2_idx_mock_sessions_expires_at ON v2_mock_test_sessions USING btree (expires_at);
CREATE INDEX v2_idx_mock_sessions_submission ON v2_mock_test_sessions USING btree (submission_id);
CREATE INDEX v2_idx_mock_sessions_user_status ON v2_mock_test_sessions USING btree (user_id, status);

-- mock_test_answers (FK → mock_test_sessions.session_id)
CREATE TABLE v2_mock_test_answers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL REFERENCES v2_mock_test_sessions(session_id),
  question_number smallint NOT NULL,
  question_id text,
  audio_url text,
  audio_duration numeric(8,2),
  transcript text,
  word_count integer,
  filler_word_count integer DEFAULT 0,
  long_pause_count integer DEFAULT 0,
  pronunciation_assessment jsonb,
  eval_status text DEFAULT 'pending',
  eval_retry_count smallint DEFAULT 0,
  eval_error text,
  skipped boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  wpm numeric(6,2),
  meta_only boolean DEFAULT false,
  unfinished_end boolean DEFAULT false,
  filler_ratio numeric(5,4),
  CONSTRAINT v2_mock_test_answers_pkey PRIMARY KEY (id),
  CONSTRAINT v2_mock_test_answers_session_id_question_number_key UNIQUE (session_id, question_number)
);
ALTER TABLE v2_mock_test_answers ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_mock_answers_insert_own ON v2_mock_test_answers FOR INSERT TO public
  WITH CHECK (EXISTS (SELECT 1 FROM v2_mock_test_sessions s WHERE s.session_id = v2_mock_test_answers.session_id AND s.user_id = auth.uid()));
CREATE POLICY v2_mock_answers_select_own ON v2_mock_test_answers FOR SELECT TO public
  USING ((EXISTS (SELECT 1 FROM v2_mock_test_sessions s WHERE s.session_id = v2_mock_test_answers.session_id AND s.user_id = auth.uid())) OR ((auth.jwt() -> 'app_metadata') ->> 'role') = 'admin');
CREATE POLICY v2_mock_answers_update_own ON v2_mock_test_answers FOR UPDATE TO public
  USING (EXISTS (SELECT 1 FROM v2_mock_test_sessions s WHERE s.session_id = v2_mock_test_answers.session_id AND s.user_id = auth.uid()));
CREATE INDEX v2_idx_mock_answers_eval_status ON v2_mock_test_answers USING btree (eval_status) WHERE eval_status <> 'completed' AND eval_status <> 'skipped';
CREATE INDEX v2_idx_mock_answers_session ON v2_mock_test_answers USING btree (session_id);

-- mock_test_evaluations
CREATE TABLE v2_mock_test_evaluations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id),
  question_number integer NOT NULL,
  question_id text NOT NULL,
  question_type text NOT NULL,
  target_grade text NOT NULL,
  model text NOT NULL DEFAULT 'gpt-4.1-mini',
  tokens_used integer NOT NULL DEFAULT 0,
  processing_time_ms integer NOT NULL DEFAULT 0,
  skipped_by_preprocess boolean NOT NULL DEFAULT false,
  evaluated_at timestamptz NOT NULL DEFAULT now(),
  checkboxes jsonb NOT NULL DEFAULT '{}',
  checkbox_type text NOT NULL DEFAULT 'INT',
  pass_count integer NOT NULL DEFAULT 0,
  fail_count integer NOT NULL DEFAULT 0,
  pass_rate numeric(5,4) NOT NULL DEFAULT 0,
  CONSTRAINT v2_mock_test_evaluations_pkey PRIMARY KEY (id),
  CONSTRAINT v2_mock_test_evaluations_session_id_question_number_key UNIQUE (session_id, question_number)
);
ALTER TABLE v2_mock_test_evaluations ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_eval_admin_select ON v2_mock_test_evaluations FOR SELECT TO public
  USING (EXISTS (SELECT 1 FROM auth.users WHERE users.id = auth.uid() AND (users.raw_app_meta_data ->> 'role') = 'admin'));
CREATE POLICY v2_eval_select_own ON v2_mock_test_evaluations FOR SELECT TO public USING (auth.uid() = user_id);
CREATE POLICY v2_eval_service_delete ON v2_mock_test_evaluations FOR DELETE TO public
  USING (current_setting('role') = 'service_role' OR auth.uid() = user_id);
CREATE POLICY v2_eval_service_insert ON v2_mock_test_evaluations FOR INSERT TO public
  WITH CHECK (current_setting('role') = 'service_role' OR auth.uid() = user_id);
CREATE INDEX v2_idx_eval_session ON v2_mock_test_evaluations USING btree (session_id);
CREATE INDEX v2_idx_eval_user ON v2_mock_test_evaluations USING btree (user_id);

-- mock_test_consults
CREATE TABLE v2_mock_test_consults (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id),
  question_number integer NOT NULL,
  question_id text NOT NULL,
  question_type text NOT NULL,
  target_grade text NOT NULL,
  fulfillment text NOT NULL,
  task_checklist jsonb NOT NULL DEFAULT '[]',
  observation text NOT NULL DEFAULT '',
  directions jsonb NOT NULL DEFAULT '[]',
  weak_points jsonb NOT NULL DEFAULT '[]',
  model text NOT NULL DEFAULT 'gpt-4.1',
  tokens_used integer NOT NULL DEFAULT 0,
  processing_time_ms integer NOT NULL DEFAULT 0,
  skipped_by_preprocess boolean NOT NULL DEFAULT false,
  evaluated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT v2_mock_test_consults_pkey PRIMARY KEY (id),
  CONSTRAINT v2_mock_test_consults_session_id_question_number_key UNIQUE (session_id, question_number)
);
ALTER TABLE v2_mock_test_consults ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_service_role_full_access_consults ON v2_mock_test_consults FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY v2_user_select_own_consults ON v2_mock_test_consults FOR SELECT TO public USING (auth.uid() = user_id);

-- mock_test_reports
CREATE TABLE v2_mock_test_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL REFERENCES v2_mock_test_sessions(session_id),
  user_id uuid NOT NULL REFERENCES auth.users(id),
  overview jsonb NOT NULL DEFAULT '{}',
  growth jsonb NOT NULL DEFAULT '{}',
  model text NOT NULL DEFAULT 'gpt-4.1',
  tokens_used integer NOT NULL DEFAULT 0,
  processing_time_ms integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  final_level text,
  target_grade text,
  rule_engine_result jsonb DEFAULT '{}',
  aggregated_checkboxes jsonb DEFAULT '{}',
  CONSTRAINT v2_mock_test_reports_pkey PRIMARY KEY (id),
  CONSTRAINT v2_mock_test_reports_session_id_key UNIQUE (session_id)
);
ALTER TABLE v2_mock_test_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_reports_admin_select ON v2_mock_test_reports FOR SELECT TO public
  USING ((SELECT ((auth.jwt() -> 'app_metadata') ->> 'role')) = 'admin');
CREATE POLICY v2_reports_select_own ON v2_mock_test_reports FOR SELECT TO public USING (auth.uid() = user_id);
CREATE POLICY v2_reports_service_delete ON v2_mock_test_reports FOR DELETE TO public USING (true);
CREATE POLICY v2_reports_service_insert ON v2_mock_test_reports FOR INSERT TO public WITH CHECK (true);
CREATE POLICY v2_reports_service_update ON v2_mock_test_reports FOR UPDATE TO public USING (true);
CREATE INDEX v2_idx_reports_session ON v2_mock_test_reports USING btree (session_id);
CREATE INDEX v2_idx_reports_user ON v2_mock_test_reports USING btree (user_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. tutoring (FK 체인: sessions → focuses → drills → attempts, retests)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE v2_tutoring_sessions (
  id text NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id),
  analyzed_session_ids text[] NOT NULL,
  current_stable_level text NOT NULL,
  ceiling_candidate_level text,
  next_step_level text NOT NULL,
  final_target_level text NOT NULL,
  stable_confidence numeric(3,2),
  floor_status jsonb,
  target_gap_summary jsonb,
  diagnosis_internal jsonb,
  top_bottlenecks jsonb,
  student_top_focuses jsonb,
  student_summary jsonb,
  prescription_json jsonb,
  status text NOT NULL DEFAULT 'diagnosing',
  model text,
  tokens_used integer,
  prompt_version text,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  CONSTRAINT v2_tutoring_sessions_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_tutoring_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_tutoring_sessions_user_all ON v2_tutoring_sessions FOR ALL TO public USING (auth.uid() = user_id);
CREATE INDEX v2_idx_tutoring_sessions_status ON v2_tutoring_sessions USING btree (status);
CREATE INDEX v2_idx_tutoring_sessions_user ON v2_tutoring_sessions USING btree (user_id);

CREATE TABLE v2_tutoring_focuses (
  id text NOT NULL,
  session_id text NOT NULL REFERENCES v2_tutoring_sessions(id),
  priority_rank integer NOT NULL,
  focus_code text NOT NULL,
  label text NOT NULL,
  reason text,
  why_now_for_target text,
  selection_policy jsonb,
  question_pool jsonb,
  drill_session_plan jsonb,
  status text NOT NULL DEFAULT 'pending',
  drill_pass_count integer NOT NULL DEFAULT 0,
  transfer_pass_count integer NOT NULL DEFAULT 0,
  retest_pass_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT v2_tutoring_focuses_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_tutoring_focuses ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_tutoring_focuses_user_all ON v2_tutoring_focuses FOR ALL TO public
  USING (session_id IN (SELECT id FROM v2_tutoring_sessions WHERE user_id = auth.uid()));
CREATE INDEX v2_idx_tutoring_focuses_session ON v2_tutoring_focuses USING btree (session_id);

CREATE TABLE v2_tutoring_drills (
  id text NOT NULL,
  focus_id text NOT NULL REFERENCES v2_tutoring_focuses(id),
  question_number integer NOT NULL,
  question_id text NOT NULL,
  question_english text NOT NULL,
  topic text,
  goal text,
  hint_level text NOT NULL,
  frame_slots jsonb,
  sample_answer text,
  pass_criteria jsonb,
  rule_only_hint text,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT v2_tutoring_drills_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_tutoring_drills ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_tutoring_drills_user_all ON v2_tutoring_drills FOR ALL TO public
  USING (focus_id IN (SELECT f.id FROM v2_tutoring_focuses f JOIN v2_tutoring_sessions s ON s.id = f.session_id WHERE s.user_id = auth.uid()));
CREATE INDEX v2_idx_tutoring_drills_focus ON v2_tutoring_drills USING btree (focus_id);

CREATE TABLE v2_tutoring_attempts (
  id text NOT NULL,
  drill_id text NOT NULL REFERENCES v2_tutoring_drills(id),
  attempt_number integer NOT NULL,
  transcript text,
  audio_url text,
  audio_duration numeric(6,1),
  word_count integer,
  wpm numeric(5,1),
  filler_word_count integer,
  filler_ratio numeric(4,3),
  long_pause_count integer,
  pronunciation_assessment jsonb,
  layer1_result jsonb,
  layer2_result jsonb,
  result text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT v2_tutoring_attempts_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_tutoring_attempts ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_tutoring_attempts_user_all ON v2_tutoring_attempts FOR ALL TO public
  USING (drill_id IN (SELECT d.id FROM v2_tutoring_drills d JOIN v2_tutoring_focuses f ON f.id = d.focus_id JOIN v2_tutoring_sessions s ON s.id = f.session_id WHERE s.user_id = auth.uid()));
CREATE INDEX v2_idx_tutoring_attempts_drill ON v2_tutoring_attempts USING btree (drill_id);

CREATE TABLE v2_tutoring_retests (
  id text NOT NULL,
  focus_id text NOT NULL REFERENCES v2_tutoring_focuses(id),
  retest_mode text NOT NULL,
  questions jsonb NOT NULL,
  results jsonb,
  overall_result text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT v2_tutoring_retests_pkey PRIMARY KEY (id)
);
ALTER TABLE v2_tutoring_retests ENABLE ROW LEVEL SECURITY;
CREATE POLICY v2_tutoring_retests_user_all ON v2_tutoring_retests FOR ALL TO public
  USING (focus_id IN (SELECT f.id FROM v2_tutoring_focuses f JOIN v2_tutoring_sessions s ON s.id = f.session_id WHERE s.user_id = auth.uid()));
CREATE INDEX v2_idx_tutoring_retests_focus ON v2_tutoring_retests USING btree (focus_id);

-- =============================================================================
-- 8. RPC 함수 (v2_ 접두사, 내부 테이블 참조도 v2_로 변경)
-- =============================================================================

-- v2_charge_balance
CREATE OR REPLACE FUNCTION public.v2_charge_balance(p_user_id uuid, p_amount_krw integer)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_new_balance INTEGER;
BEGIN
  UPDATE v2_user_credits
  SET balance_krw = balance_krw + p_amount_krw,
      updated_at = NOW()
  WHERE user_id = p_user_id
  RETURNING balance_krw INTO v_new_balance;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'v2_user_credits not found for user %', p_user_id;
  END IF;

  RETURN v_new_balance;
END;
$function$;

-- v2_check_balance
CREATE OR REPLACE FUNCTION public.v2_check_balance(p_user_id uuid)
RETURNS integer
LANGUAGE sql
STABLE SECURITY DEFINER
AS $function$
  SELECT COALESCE(balance_krw, 0)
  FROM v2_user_credits
  WHERE user_id = p_user_id;
$function$;

-- v2_consume_mock_exam_credit
CREATE OR REPLACE FUNCTION public.v2_consume_mock_exam_credit(p_user_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_plan_credits INTEGER;
  v_credits INTEGER;
BEGIN
  SELECT plan_mock_exam_credits, mock_exam_credits
  INTO v_plan_credits, v_credits
  FROM v2_user_credits
  WHERE user_id = p_user_id
  FOR UPDATE;

  IF v_plan_credits > 0 THEN
    UPDATE v2_user_credits
    SET plan_mock_exam_credits = plan_mock_exam_credits - 1,
        updated_at = NOW()
    WHERE user_id = p_user_id;
    RETURN true;
  END IF;

  IF v_credits > 0 THEN
    UPDATE v2_user_credits
    SET mock_exam_credits = mock_exam_credits - 1,
        updated_at = NOW()
    WHERE user_id = p_user_id;
    RETURN true;
  END IF;

  RETURN false;
END;
$function$;

-- v2_consume_script_credit
CREATE OR REPLACE FUNCTION public.v2_consume_script_credit(p_user_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_plan_credits INTEGER;
  v_credits INTEGER;
BEGIN
  SELECT plan_script_credits, script_credits
  INTO v_plan_credits, v_credits
  FROM v2_user_credits
  WHERE user_id = p_user_id
  FOR UPDATE;

  IF v_plan_credits > 0 THEN
    UPDATE v2_user_credits
    SET plan_script_credits = plan_script_credits - 1,
        updated_at = NOW()
    WHERE user_id = p_user_id;
    RETURN true;
  END IF;

  IF v_credits > 0 THEN
    UPDATE v2_user_credits
    SET script_credits = script_credits - 1,
        updated_at = NOW()
    WHERE user_id = p_user_id;
    RETURN true;
  END IF;

  RETURN false;
END;
$function$;

-- v2_consume_tutoring_credit
CREATE OR REPLACE FUNCTION public.v2_consume_tutoring_credit(p_user_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_plan_credits INTEGER;
  v_credits INTEGER;
BEGIN
  SELECT plan_tutoring_credits, tutoring_credits
  INTO v_plan_credits, v_credits
  FROM v2_user_credits
  WHERE user_id = p_user_id
  FOR UPDATE;

  IF v_plan_credits > 0 THEN
    UPDATE v2_user_credits
    SET plan_tutoring_credits = plan_tutoring_credits - 1,
        updated_at = NOW()
    WHERE user_id = p_user_id;
    RETURN true;
  END IF;

  IF v_credits > 0 THEN
    UPDATE v2_user_credits
    SET tutoring_credits = tutoring_credits - 1,
        updated_at = NOW()
    WHERE user_id = p_user_id;
    RETURN true;
  END IF;

  RETURN false;
END;
$function$;

-- v2_deduct_usage_cost
CREATE OR REPLACE FUNCTION public.v2_deduct_usage_cost(p_user_id uuid, p_cost_krw integer)
RETURNS TABLE(success boolean, remaining_balance integer)
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_current_balance INTEGER;
BEGIN
  SELECT balance_krw INTO v_current_balance
  FROM v2_user_credits
  WHERE user_id = p_user_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN QUERY SELECT false, 0;
    RETURN;
  END IF;

  IF v_current_balance < p_cost_krw THEN
    RETURN QUERY SELECT false, v_current_balance;
    RETURN;
  END IF;

  UPDATE v2_user_credits
  SET balance_krw = balance_krw - p_cost_krw,
      updated_at = NOW()
  WHERE user_id = p_user_id;

  RETURN QUERY SELECT true, (v_current_balance - p_cost_krw);
END;
$function$;

-- v2_expire_beta_plans
CREATE OR REPLACE FUNCTION public.v2_expire_beta_plans()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_count INTEGER;
BEGIN
  UPDATE v2_user_credits
  SET current_plan = 'free',
      plan_mock_exam_credits = 0,
      plan_script_credits = 0,
      plan_tutoring_credits = 0,
      plan_expires_at = NULL,
      updated_at = NOW()
  WHERE current_plan = 'beta'
    AND (plan_expires_at IS NULL OR plan_expires_at < NOW());

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$function$;

-- v2_approve_beta_application
CREATE OR REPLACE FUNCTION public.v2_approve_beta_application(p_application_id uuid, p_admin_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_user_id UUID;
  v_current_count INTEGER;
  v_max_beta INTEGER := 100;
  v_beta_expires TIMESTAMPTZ := '2026-04-30 23:59:59+09'::TIMESTAMPTZ;
BEGIN
  SELECT user_id INTO v_user_id
  FROM v2_beta_applications
  WHERE id = p_application_id AND status = 'pending'
  FOR UPDATE;

  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', '유효하지 않은 신청이거나 이미 처리되었습니다');
  END IF;

  SELECT COUNT(*) INTO v_current_count
  FROM v2_beta_applications
  WHERE status = 'approved';

  IF v_current_count >= v_max_beta THEN
    RETURN jsonb_build_object('success', false, 'error', '베타 정원(100명)이 마감되었습니다');
  END IF;

  UPDATE v2_beta_applications
  SET status = 'approved',
      reviewed_by = p_admin_id,
      reviewed_at = NOW(),
      updated_at = NOW()
  WHERE id = p_application_id;

  UPDATE v2_user_credits
  SET current_plan = 'beta',
      plan_mock_exam_credits = 3,
      plan_script_credits = 15,
      plan_tutoring_credits = 0,
      plan_expires_at = v_beta_expires,
      updated_at = NOW()
  WHERE user_id = v_user_id;

  RETURN jsonb_build_object(
    'success', true,
    'user_id', v_user_id::text,
    'remaining', v_max_beta - v_current_count - 1
  );
END;
$function$;

-- v2_get_beta_stats
CREATE OR REPLACE FUNCTION public.v2_get_beta_stats()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_total INTEGER;
  v_approved INTEGER;
  v_pending INTEGER;
  v_rejected INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_total FROM v2_beta_applications;
  SELECT COUNT(*) INTO v_approved FROM v2_beta_applications WHERE status = 'approved';
  SELECT COUNT(*) INTO v_pending FROM v2_beta_applications WHERE status = 'pending';
  SELECT COUNT(*) INTO v_rejected FROM v2_beta_applications WHERE status = 'rejected';

  RETURN jsonb_build_object(
    'total', v_total,
    'approved', v_approved,
    'pending', v_pending,
    'rejected', v_rejected,
    'remaining', 100 - v_approved
  );
END;
$function$;

-- v2_get_dau_count (auth.users는 변경 없음)
CREATE OR REPLACE FUNCTION public.v2_get_dau_count(target_date date)
RETURNS TABLE(count bigint)
LANGUAGE sql
SECURITY DEFINER
AS $function$
  SELECT COUNT(*)::BIGINT
  FROM auth.users
  WHERE last_sign_in_at::date = target_date;
$function$;

-- v2_get_user_cost_summary
CREATE OR REPLACE FUNCTION public.v2_get_user_cost_summary(p_user_id uuid, p_from timestamptz DEFAULT (now() - '30 days'::interval), p_to timestamptz DEFAULT now())
RETURNS TABLE(session_type text, total_calls bigint, total_cost_usd numeric, total_cost_krw numeric)
LANGUAGE sql
STABLE
AS $function$
  SELECT
    session_type,
    COUNT(*) AS total_calls,
    SUM(cost_usd) AS total_cost_usd,
    ROUND(SUM(cost_usd) * 1400, 0) AS total_cost_krw
  FROM v2_api_usage_logs
  WHERE user_id = p_user_id
    AND created_at >= p_from
    AND created_at < p_to
  GROUP BY session_type
  ORDER BY total_cost_krw DESC;
$function$;

-- v2_get_user_usage_summary
CREATE OR REPLACE FUNCTION public.v2_get_user_usage_summary(p_user_id uuid, p_from timestamptz DEFAULT (now() - '30 days'::interval), p_to timestamptz DEFAULT now())
RETURNS TABLE(session_type text, feature text, call_count bigint, total_cost_usd numeric, total_tokens_in bigint, total_tokens_out bigint, total_audio_sec numeric)
LANGUAGE sql
STABLE
AS $function$
  SELECT
    session_type,
    feature,
    COUNT(*) AS call_count,
    SUM(cost_usd) AS total_cost_usd,
    SUM(tokens_in) AS total_tokens_in,
    SUM(tokens_out) AS total_tokens_out,
    SUM(audio_duration_sec) AS total_audio_sec
  FROM v2_api_usage_logs
  WHERE user_id = p_user_id
    AND created_at >= p_from
    AND created_at < p_to
  GROUP BY session_type, feature
  ORDER BY total_cost_usd DESC;
$function$;

-- v2_increment_completed_prescriptions
CREATE OR REPLACE FUNCTION public.v2_increment_completed_prescriptions(p_session_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  UPDATE v2_tutoring_sessions
  SET completed_prescriptions = completed_prescriptions + 1
  WHERE id = p_session_id::text;
END;
$function$;

-- v2_increment_script_credits
CREATE OR REPLACE FUNCTION public.v2_increment_script_credits(p_user_id uuid, p_amount integer)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  UPDATE v2_user_credits
  SET script_credits = script_credits + p_amount,
      updated_at = NOW()
  WHERE user_id = p_user_id;
END;
$function$;

-- v2_polar_admin_adjust_balance
CREATE OR REPLACE FUNCTION public.v2_polar_admin_adjust_balance(p_user_id uuid, p_amount integer, p_description text DEFAULT '관리자 조정')
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_new_balance INTEGER;
BEGIN
  UPDATE v2_polar_balances
  SET balance_krw = GREATEST(balance_krw + p_amount, 0),
      updated_at = NOW()
  WHERE user_id = p_user_id
  RETURNING balance_krw INTO v_new_balance;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'no_balance');
  END IF;

  INSERT INTO v2_polar_transactions (user_id, type, amount, balance_after, description)
  VALUES (p_user_id, 'admin_adjust', p_amount, v_new_balance, p_description);

  RETURN jsonb_build_object('success', true, 'balance', v_new_balance);
END;
$function$;

-- v2_polar_charge_balance
CREATE OR REPLACE FUNCTION public.v2_polar_charge_balance(p_user_id uuid, p_amount_krw integer, p_description text DEFAULT '크레딧 충전', p_ref_id text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_new_balance INTEGER;
BEGIN
  UPDATE v2_polar_balances
  SET balance_krw = balance_krw + p_amount_krw,
      total_charged = total_charged + p_amount_krw,
      updated_at = NOW()
  WHERE user_id = p_user_id
  RETURNING balance_krw INTO v_new_balance;

  IF NOT FOUND THEN
    INSERT INTO v2_polar_balances (user_id, balance_krw, total_charged, total_used)
    VALUES (p_user_id, p_amount_krw, p_amount_krw, 0)
    RETURNING balance_krw INTO v_new_balance;
  END IF;

  INSERT INTO v2_polar_transactions (user_id, type, amount, balance_after, description, ref_id)
  VALUES (p_user_id, 'charge', p_amount_krw, v_new_balance, p_description, p_ref_id);

  RETURN jsonb_build_object('success', true, 'balance', v_new_balance);
END;
$function$;

-- v2_polar_deduct_balance
CREATE OR REPLACE FUNCTION public.v2_polar_deduct_balance(p_user_id uuid, p_cost_krw integer, p_description text DEFAULT '크레딧 사용', p_ref_id text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_current_balance INTEGER;
  v_new_balance INTEGER;
BEGIN
  SELECT balance_krw INTO v_current_balance
  FROM v2_polar_balances
  WHERE user_id = p_user_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'no_balance', 'balance', 0);
  END IF;

  IF v_current_balance < p_cost_krw THEN
    RETURN jsonb_build_object('success', false, 'error', 'insufficient', 'balance', v_current_balance);
  END IF;

  v_new_balance := v_current_balance - p_cost_krw;
  UPDATE v2_polar_balances
  SET balance_krw = v_new_balance,
      total_used = total_used + p_cost_krw,
      updated_at = NOW()
  WHERE user_id = p_user_id;

  INSERT INTO v2_polar_transactions (user_id, type, amount, balance_after, description, ref_id)
  VALUES (p_user_id, 'usage', -p_cost_krw, v_new_balance, p_description, p_ref_id);

  RETURN jsonb_build_object('success', true, 'balance', v_new_balance);
END;
$function$;

-- v2_polar_get_balance
CREATE OR REPLACE FUNCTION public.v2_polar_get_balance(p_user_id uuid)
RETURNS integer
LANGUAGE sql
STABLE SECURITY DEFINER
AS $function$
  SELECT COALESCE(balance_krw, 0)
  FROM v2_polar_balances
  WHERE user_id = p_user_id;
$function$;

-- v2_polar_refund_balance
CREATE OR REPLACE FUNCTION public.v2_polar_refund_balance(p_user_id uuid, p_amount_krw integer, p_description text DEFAULT '크레딧 환불', p_ref_id text DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_new_balance INTEGER;
BEGIN
  UPDATE v2_polar_balances
  SET balance_krw = balance_krw + p_amount_krw,
      total_used = GREATEST(total_used - p_amount_krw, 0),
      updated_at = NOW()
  WHERE user_id = p_user_id
  RETURNING balance_krw INTO v_new_balance;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'no_balance');
  END IF;

  INSERT INTO v2_polar_transactions (user_id, type, amount, balance_after, description, ref_id)
  VALUES (p_user_id, 'refund', p_amount_krw, v_new_balance, p_description, p_ref_id);

  RETURN jsonb_build_object('success', true, 'balance', v_new_balance);
END;
$function$;

-- v2_process_payment
CREATE OR REPLACE FUNCTION public.v2_process_payment(
  p_user_id uuid, p_payment_id text, p_product_id text, p_order_name text, p_amount integer,
  p_pg_provider text DEFAULT NULL, p_pg_tx_id text DEFAULT NULL, p_pay_method text DEFAULT NULL,
  p_paid_at timestamptz DEFAULT NULL, p_receipt_url text DEFAULT NULL,
  p_is_plan boolean DEFAULT false, p_plan text DEFAULT 'free', p_plan_months integer DEFAULT 0,
  p_mock_exam_credits integer DEFAULT 0, p_script_credits integer DEFAULT 0, p_tutoring_credits integer DEFAULT 0
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_order_id UUID;
  v_expires_at TIMESTAMPTZ;
BEGIN
  INSERT INTO v2_orders (
    user_id, product_id, order_name, amount, status,
    payment_id, pg_provider, pg_tx_id, pay_method, paid_at, receipt_url
  ) VALUES (
    p_user_id, p_product_id, p_order_name, p_amount, 'paid',
    p_payment_id, p_pg_provider, p_pg_tx_id, p_pay_method,
    COALESCE(p_paid_at, NOW()), p_receipt_url
  )
  ON CONFLICT (payment_id) DO NOTHING
  RETURNING id INTO v_order_id;

  IF v_order_id IS NULL THEN
    RETURN jsonb_build_object('success', true, 'duplicate', true);
  END IF;

  IF p_is_plan THEN
    v_expires_at := NOW() + (p_plan_months || ' months')::INTERVAL;
    UPDATE v2_user_credits SET
      current_plan = p_plan,
      plan_mock_exam_credits = p_mock_exam_credits,
      plan_script_credits = p_script_credits,
      plan_tutoring_credits = p_tutoring_credits,
      plan_expires_at = v_expires_at,
      updated_at = NOW()
    WHERE user_id = p_user_id;
  ELSE
    UPDATE v2_user_credits SET
      mock_exam_credits = mock_exam_credits + p_mock_exam_credits,
      script_credits = script_credits + p_script_credits,
      tutoring_credits = tutoring_credits + p_tutoring_credits,
      updated_at = NOW()
    WHERE user_id = p_user_id;
  END IF;

  RETURN jsonb_build_object('success', true, 'order_id', v_order_id::text);
END;
$function$;

-- v2_process_polar_payment
CREATE OR REPLACE FUNCTION public.v2_process_polar_payment(p_user_id uuid, p_polar_checkout_id text, p_polar_product_id text, p_product_type text, p_amount integer, p_credit_amount integer)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_order_id UUID;
  v_new_balance INTEGER;
BEGIN
  INSERT INTO v2_polar_orders (
    user_id, polar_checkout_id, polar_product_id,
    product_type, amount, credit_amount, status
  ) VALUES (
    p_user_id, p_polar_checkout_id, p_polar_product_id,
    p_product_type, p_amount, p_credit_amount, 'paid'
  )
  ON CONFLICT (polar_checkout_id) DO NOTHING
  RETURNING id INTO v_order_id;

  IF v_order_id IS NULL THEN
    RETURN jsonb_build_object('success', true, 'duplicate', true);
  END IF;

  IF p_credit_amount > 0 THEN
    SELECT (v2_polar_charge_balance(p_user_id, p_credit_amount, '크레딧 충전', p_polar_checkout_id))->>'balance'
    INTO v_new_balance;
  END IF;

  RETURN jsonb_build_object(
    'success', true,
    'order_id', v_order_id::text,
    'balance', COALESCE(v_new_balance, 0)
  );
END;
$function$;

-- v2_refund_mock_exam_credit
CREATE OR REPLACE FUNCTION public.v2_refund_mock_exam_credit(p_user_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  UPDATE v2_user_credits
  SET mock_exam_credits = mock_exam_credits + 1,
      updated_at = NOW()
  WHERE user_id = p_user_id;
END;
$function$;

-- v2_refund_script_credit
CREATE OR REPLACE FUNCTION public.v2_refund_script_credit(p_user_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  UPDATE v2_user_credits
  SET script_credits = script_credits + 1,
      updated_at = NOW()
  WHERE user_id = p_user_id;
END;
$function$;

-- v2_refund_tutoring_credit
CREATE OR REPLACE FUNCTION public.v2_refund_tutoring_credit(p_user_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  UPDATE v2_user_credits
  SET tutoring_credits = tutoring_credits + 1,
      updated_at = NOW()
  WHERE user_id = p_user_id;
END;
$function$;

-- v2_refund_usage_cost
CREATE OR REPLACE FUNCTION public.v2_refund_usage_cost(p_user_id uuid, p_cost_krw integer)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_new_balance INTEGER;
BEGIN
  UPDATE v2_user_credits
  SET balance_krw = balance_krw + p_cost_krw,
      updated_at = NOW()
  WHERE user_id = p_user_id
  RETURNING balance_krw INTO v_new_balance;

  RETURN COALESCE(v_new_balance, 0);
END;
$function$;

-- =============================================================================
-- 9. 트리거 함수 (v2_)
-- 주의: handle_new_user / handle_new_user_credits / handle_new_user_polar_balance는
-- auth.users INSERT 트리거로 동작하므로, v2_ 트리거는 별도 바인딩이 필요합니다.
-- 여기서는 함수만 생성하고, 트리거 바인딩은 수동으로 설정하세요.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.v2_handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
  INSERT INTO public.v2_profiles (id, email)
  VALUES (NEW.id, NEW.email)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.v2_handle_new_user_credits()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
  INSERT INTO public.v2_user_credits (
    user_id, current_plan,
    plan_mock_exam_credits, plan_script_credits,
    mock_exam_credits, script_credits
  )
  VALUES (NEW.id, 'free', 0, 0, 0, 0)
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.v2_handle_new_user_polar_balance()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.v2_polar_balances (user_id, balance_krw, total_charged, total_used)
  VALUES (NEW.id, 0, 0, 0)
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$function$;

-- v2_update_updated_at (범용 트리거)
CREATE OR REPLACE FUNCTION public.v2_update_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;

-- v2_update_beta_applications_updated_at
CREATE OR REPLACE FUNCTION public.v2_update_beta_applications_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;

-- =============================================================================
-- 완료: 모든 v2_ 테이블, 인덱스, RLS 정책, RPC 함수 생성
-- system_settings 제외 (v1과 공유)
-- =============================================================================
