-- =============================================
-- 089: talklish_completed_combos — Talklish 수요일 OPIc 학습 이력
-- =============================================
-- 스터디 모임 단위 전역 완료 기록.
-- Talklish는 단일 스터디(패널 멤버 1세트, 콘텐츠 1세트) 운영 모델이라
-- 누가 진행자든 같은 완료 목록을 보고/표시한다.
--
-- 시그니처 = question_ids 정렬·조인 (study-group.ts buildComboSignature)
-- 한 콤보는 전역 1행만 존재 — UNIQUE(combo_sig).
-- 다시 완료를 누르면 completed_at만 갱신 (upsert).
-- completed_by 는 감사·롤백용 보조 정보 (누가 마지막으로 완료 표시했는지).

CREATE TABLE IF NOT EXISTS talklish_completed_combos (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  combo_sig    text NOT NULL UNIQUE,
  category     text NOT NULL,
  topic        text NOT NULL,
  completed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  completed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tcc_topic
  ON talklish_completed_combos (topic);

COMMENT ON TABLE talklish_completed_combos IS
  'Talklish 수요일 OPIc 콤보 학습 이력 — 스터디 모임 단위 전역 1세트 (진행자 무관)';
COMMENT ON COLUMN talklish_completed_combos.combo_sig IS
  '정렬된 question_ids 시그니처 (study-group.ts buildComboSignature 와 동일)';
COMMENT ON COLUMN talklish_completed_combos.completed_by IS
  '감사용 — 마지막으로 완료 표시 누른 사용자';

-- RLS — 로그인한 패널 접근 사용자라면 누구나 SELECT/INSERT/DELETE
--       (Talklish는 권한 게이트가 requireStudyPanelAccess로 이미 한 번 걸림)
ALTER TABLE talklish_completed_combos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tcc_authed_select ON talklish_completed_combos;
CREATE POLICY tcc_authed_select ON talklish_completed_combos
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS tcc_authed_insert ON talklish_completed_combos;
CREATE POLICY tcc_authed_insert ON talklish_completed_combos
  FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS tcc_authed_update ON talklish_completed_combos;
CREATE POLICY tcc_authed_update ON talklish_completed_combos
  FOR UPDATE
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS tcc_authed_delete ON talklish_completed_combos;
CREATE POLICY tcc_authed_delete ON talklish_completed_combos
  FOR DELETE
  USING (auth.uid() IS NOT NULL);
