-- =============================================
-- 095: talklish_completed_podcasts — Talklish 월요일 Podcast 학습 이력
-- =============================================
-- 089(완료 콤보)와 동일 모델: 스터디 모임 단위 전역 완료 기록.
-- Talklish는 단일 스터디 운영이라 누가 진행자든 같은 완료 목록을 보고/표시한다.
-- 한 자료(에피소드)는 전역 1행만 — UNIQUE(podcast_id).
-- 다시 완료를 누르면 completed_at 만 갱신 (upsert). 완료 취소 시 row 삭제.

CREATE TABLE IF NOT EXISTS talklish_completed_podcasts (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  podcast_id   uuid NOT NULL UNIQUE REFERENCES study_podcasts(id) ON DELETE CASCADE,
  completed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  completed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tcp_podcast
  ON talklish_completed_podcasts (podcast_id);

COMMENT ON TABLE talklish_completed_podcasts IS
  'Talklish 월요일 Podcast 자료 학습 이력 — 스터디 모임 단위 전역 1세트 (진행자 무관)';
COMMENT ON COLUMN talklish_completed_podcasts.podcast_id IS
  'study_podcasts.id — 완료한 자료(에피소드). 자료 삭제 시 함께 삭제(CASCADE).';
COMMENT ON COLUMN talklish_completed_podcasts.completed_by IS
  '감사용 — 마지막으로 완료 표시 누른 사용자';

-- RLS — 로그인한 패널 접근 사용자라면 누구나 SELECT/INSERT/UPDATE/DELETE
--       (Talklish는 권한 게이트가 진입 단계에서 이미 한 번 걸림. 089와 동일 정책)
ALTER TABLE talklish_completed_podcasts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tcp_authed_select ON talklish_completed_podcasts;
CREATE POLICY tcp_authed_select ON talklish_completed_podcasts
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS tcp_authed_insert ON talklish_completed_podcasts;
CREATE POLICY tcp_authed_insert ON talklish_completed_podcasts
  FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS tcp_authed_update ON talklish_completed_podcasts;
CREATE POLICY tcp_authed_update ON talklish_completed_podcasts
  FOR UPDATE
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS tcp_authed_delete ON talklish_completed_podcasts;
CREATE POLICY tcp_authed_delete ON talklish_completed_podcasts
  FOR DELETE
  USING (auth.uid() IS NOT NULL);
