-- =============================================
-- 098: Talklish 수요일 OPIc — 세션 · 답변 · 가이드 캐시
-- =============================================
-- 수요일 오프라인 OPIc 스터디 개선:
--   1) talklish_sessions          — "하루 = 1세션" (session_date UNIQUE)
--   2) talklish_answers           — 룰렛 발표자 답변 + AI 코칭 영구 저장 (휘발 → 영구)
--   3) talklish_combo_guide_cache — 콤보별 AI 답변 가이드 영구 캐시 (Talklish 전용)
--
-- 권한: Talklish는 requireStudyPanelAccess 게이트가 Server Action에서 한 번 걸리므로
--       RLS는 로그인 사용자(auth.uid() IS NOT NULL) 기준으로 단순화 (089 패턴).
-- 콤보 sig = 정렬된 question_ids 시그니처 (study-group.ts buildComboSignature 와 동일).
-- 가이드 캐시는 talklish-guide EF(service role)가 UPSERT, 클라이언트는 SELECT.

BEGIN;

-- ── 1. 세션 (하루 1세션) ─────────────────────────────
CREATE TABLE IF NOT EXISTS talklish_sessions (
  id           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  session_date date NOT NULL UNIQUE,                 -- 하루 1세션
  started_at   timestamptz NOT NULL DEFAULT now(),
  ended_at     timestamptz,                          -- 종료(정리) 완료 시각
  created_by   uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE talklish_sessions IS
  'Talklish 수요일 스터디 세션 — 하루 1세션(session_date UNIQUE), 그날 여러 콤보가 한 세션에 누적';

-- ── 2. 발표자 답변 + AI 코칭 ─────────────────────────
CREATE TABLE IF NOT EXISTS talklish_answers (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id       uuid NOT NULL REFERENCES talklish_sessions(id) ON DELETE CASCADE,
  panel_member_id  uuid NOT NULL REFERENCES study_panel_members(id) ON DELETE CASCADE,  -- 발표자
  user_id          uuid REFERENCES auth.users(id) ON DELETE SET NULL,                   -- 발표자 계정(개인 히스토리용, 없을 수 있음)
  combo_sig        text NOT NULL,
  category         text,
  topic            text,
  question_id      text NOT NULL,        -- questions.id (text 새 ID 체계)
  question_idx     int,                  -- 콤보 내 순서(0~3)
  question_type    text,
  question_english text,                 -- 질문 스냅샷 (히스토리 표시용, questions 조인 불필요)
  question_korean  text,
  audio_url        text,
  transcript       text,
  coaching         jsonb,                -- talklish-coach EF 결과 (summary/good_points/improve_points 등)
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ta_session ON talklish_answers(session_id);
CREATE INDEX IF NOT EXISTS idx_ta_member  ON talklish_answers(panel_member_id);
CREATE INDEX IF NOT EXISTS idx_ta_user    ON talklish_answers(user_id);

COMMENT ON TABLE talklish_answers IS
  'Talklish 수요일 룰렛 발표자 답변 + AI 코칭 영구 저장 (멤버별 정리/개인 히스토리용)';
COMMENT ON COLUMN talklish_answers.panel_member_id IS '발표자 패널 멤버 (멤버별 탭 식별)';
COMMENT ON COLUMN talklish_answers.user_id IS '발표자 계정 (개인 히스토리 접속용, NULL 가능)';
COMMENT ON COLUMN talklish_answers.coaching IS 'talklish-coach EF 코칭 결과 JSON';

-- ── 3. 콤보 가이드 캐시 (Talklish 전용) ──────────────
-- guide jsonb 구조:
--   { "intro": string,
--     "questions": [
--       { "question_idx": int, "type_label": string,
--         "answer_flow": string[],            -- 답변 흐름 2~3단계
--         "vocab": [{ "en": string, "ko": string }],  -- 추천 어휘·표현 4~6개
--         "example": string }                 -- 예시 문장 1개 (선택)
--     ] }
CREATE TABLE IF NOT EXISTS talklish_combo_guide_cache (
  sig            text PRIMARY KEY,
  category       text,
  topic          text,
  guide          jsonb NOT NULL,
  prompt_version int NOT NULL DEFAULT 1,
  generated_at   timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE talklish_combo_guide_cache IS
  'Talklish 수요일 콤보별 AI 답변 가이드 영구 캐시 (sig 기준, 같은 콤보 재사용 시 무료)';

-- ── RLS (089 패턴 — 로그인 사용자, 권한 게이트는 SA) ──
ALTER TABLE talklish_sessions          ENABLE ROW LEVEL SECURITY;
ALTER TABLE talklish_answers           ENABLE ROW LEVEL SECURITY;
ALTER TABLE talklish_combo_guide_cache ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ts_authed_all ON talklish_sessions;
CREATE POLICY ts_authed_all ON talklish_sessions
  FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS ta_authed_all ON talklish_answers;
CREATE POLICY ta_authed_all ON talklish_answers
  FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS tcgc_authed_select ON talklish_combo_guide_cache;
CREATE POLICY tcgc_authed_select ON talklish_combo_guide_cache
  FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS tcgc_authed_write ON talklish_combo_guide_cache;
CREATE POLICY tcgc_authed_write ON talklish_combo_guide_cache
  FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

COMMIT;
